In [142]:
import pandas as pd
df = pd.read_csv("stroke.csv")

In [143]:
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [144]:


print("FIRST 5 ROWS")
print(df.head())

print("\nLAST 5 ROWS")
print(df.tail())

print("\nSHAPE")
print(df.shape)

print("\nCOLUMNS")
print(df.columns)

print("\nINFO")
print(df.info())

print("\nDescriptive statistics :")
df.describe()

FIRST 5 ROWS
      id  gender   age  hypertension  heart_disease ever_married  \
0   9046    Male  67.0             0              1          Yes
1  51676  Female  61.0             0              0          Yes
2  31112    Male  80.0             0              1          Yes
3  60182  Female  49.0             0              0          Yes
4   1665  Female  79.0             1              0          Yes

       work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0        Private          Urban             228.69  36.6  formerly smoked
1  Self-employed          Rural             202.21   NaN     never smoked
2        Private          Rural             105.92  32.5     never smoked
3        Private          Urban             171.23  34.4           smokes
4  Self-employed          Rural             174.12  24.0     never smoked

   stroke
0       1
1       1
2       1
3       1
4       1

LAST 5 ROWS
         id  gender   age  hypertension  heart_disease ever_married  \
5105  18234  Female  80.0             1              0          Yes
5106  44873  Female  81.0             0              0          Yes
5107  19723  Female  35.0             0              0          Yes
5108  37544    Male  51.0             0              0          Yes
5109  44679  Female  44.0             0              0          Yes

          work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
5105        Private          Urban              83.75   NaN     never smoked
5106  Self-employed          Urban             125.20  40.0     never smoked
5107  Self-employed          Rural              82.99  30.6     never smoked
5108        Private          Rural             166.29  25.6  formerly smoked
5109       Govt_job          Urban              85.28  26.2          Unknown

      stroke
5105       0
5106       0
5107       0
5108       0
5109       0

SHAPE
(5110, 12)

COLUMNS
Index(['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status', 'stroke'],
      dtype='object')

INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   object
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5110 non-null   object
 6   work_type          5110 non-null   object
 7   Residence_type     5110 non-null   object
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object
 11  stroke             5110 non-null   int64
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB
None

Descriptive statistics :

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke
count,5110.000000,5110.000000,5110.000000,5110.000000,5110.000000,4909.000000,5110.000000
mean,36517.829354,43.226614,0.097456,0.054012,106.147677,28.893237,0.048728
std,21161.721625,22.612647,0.296607,0.226063,45.283560,7.854067,0.215320
min,67.000000,0.080000,0.000000,0.000000,55.120000,10.300000,0.000000
25%,17741.250000,25.000000,0.000000,0.000000,77.245000,23.500000,0.000000
50%,36932.000000,45.000000,0.000000,0.000000,91.885000,28.100000,0.000000
75%,54682.000000,61.000000,0.000000,0.000000,114.090000,33.100000,0.000000
max,72940.000000,82.000000,1.000000,1.000000,271.740000,97.600000,1.000000

In [145]:
df.shape

(5110, 12)

In [146]:
print("\nMissing value count per column:")
print(df.isnull().sum())

Missing value count per column:
id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [147]:
df['bmi'] = df['bmi'].fillna(df['bmi'].mean())
df.isnull().sum()

id                   0
gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [148]:
df=df.drop_duplicates()

df.duplicated().sum()

np.int64(0)

In [149]:
df.dtypes

id                     int64
gender                object
age                  float64
hypertension           int64
heart_disease          int64
ever_married          object
work_type             object
Residence_type        object
avg_glucose_level    float64
bmi                  float64
smoking_status        object
stroke                 int64
dtype: object

In [150]:
df['age'] = df['age'].astype(int)
df['gender'] = df['gender'].astype(str)
df['ever_married'] = df['ever_married'].astype(str)
df['work_type'] = df['work_type'].astype(str)
df['Residence_type'] = df['Residence_type'].astype(str)
df['smoking_status'] = df['smoking_status'].astype(str)

In [151]:






Q1 = df['bmi'].quantile(0.25)
Q3 = df['bmi'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df['bmi'] < lower) | (df['bmi'] > upper)]

print(f"bmi: {len(outliers)} outliers")
outliers[['id','age', 'bmi','stroke','avg_glucose_level']]

bmi: 126 outliers

         id  age   bmi  stroke  avg_glucose_level
21    13861   52  48.9       1             233.29
66    17004   70  47.5       1             221.58
113   41069   45  56.6       1             224.10
254   32257   47  50.1       0             210.95
258   28674   74  54.6       0             205.84
...     ...  ...   ...     ...                ...
4906  72696   53  54.1       0              70.51
4952  16245   51  56.6       0             211.83
5009  40732   50  49.5       0             126.85
5057  38349   49  47.6       0              69.92
5103  22127   18  46.9       0              82.85

[126 rows x 5 columns]

In [152]:

Q1 = df['age'].quantile(0.25)
Q3 = df['age'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df['age'] < lower) | (df['age'] > upper)]

print(f"age: {len(outliers)} outliers")
outliers[['id','age', 'bmi','stroke','avg_glucose_level']]

age: 0 outliers

Empty DataFrame
Columns: [id, age, bmi, stroke, avg_glucose_level]
Index: []

In [153]:

Q1 = df['avg_glucose_level'].quantile(0.25)
Q3 = df['avg_glucose_level'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df['avg_glucose_level'] < lower) | (df['avg_glucose_level'] > upper)]

print(f"avg_glucose_level: {len(outliers)} outliers")
outliers[['id','age', 'bmi','stroke','avg_glucose_level']]

avg_glucose_level: 627 outliers

         id  age        bmi  stroke  avg_glucose_level
0      9046   67  36.600000       1             228.69
1     51676   61  28.893237       1             202.21
3     60182   49  34.400000       1             171.23
4      1665   79  24.000000       1             174.12
5     56669   81  29.000000       1             186.21
...     ...  ...        ...     ...                ...
5061  38009   41  32.300000       0             223.78
5062  11184   82  36.900000       0             211.58
5063  68967   39  27.700000       0             179.38
5064  66684   70  24.300000       0             193.88
5076  39935   34  23.000000       0             174.37

[627 rows x 5 columns]

In [154]:
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67,0,1,Yes,Private,Urban,228.69,36.600000,formerly smoked,1
1,51676,Female,61,0,0,Yes,Self-employed,Rural,202.21,28.893237,never smoked,1
2,31112,Male,80,0,1,Yes,Private,Rural,105.92,32.500000,never smoked,1
3,60182,Female,49,0,0,Yes,Private,Urban,171.23,34.400000,smokes,1
4,1665,Female,79,1,0,Yes,Self-employed,Rural,174.12,24.000000,never smoked,1

In [155]:
df['gender'].value_counts()

gender
Female    2994
Male      2115
Other        1
Name: count, dtype: int64

In [156]:
df['stroke'].value_counts()

stroke
0    4861
1     249
Name: count, dtype: int64

In [157]:
df['hypertension'].value_counts()

hypertension
0    4612
1     498
Name: count, dtype: int64

In [158]:
df['heart_disease'].value_counts()

heart_disease
0    4834
1     276
Name: count, dtype: int64

In [159]:
df['ever_married'].value_counts()

ever_married
Yes    3353
No     1757
Name: count, dtype: int64

In [160]:
df['smoking_status'].value_counts()

smoking_status
never smoked       1892
Unknown            1544
formerly smoked     885
smokes              789
Name: count, dtype: int64

In [161]:
df['Residence_type'].value_counts()

Residence_type
Urban    2596
Rural    2514
Name: count, dtype: int64

In [162]:
df['work_type'].value_counts()

work_type
Private          2925
Self-employed     819
children          687
Govt_job          657
Never_worked       22
Name: count, dtype: int64

In [163]:
df = df.drop(columns=['id'])

In [164]:
df = pd.get_dummies(df, columns=['gender', 'work_type'],drop_first=True   )
print(df.head())
print(df.shape)

   age  hypertension  heart_disease ever_married Residence_type  \
0   67             0              1          Yes          Urban
1   61             0              0          Yes          Rural
2   80             0              1          Yes          Rural
3   49             0              0          Yes          Urban
4   79             1              0          Yes          Rural

   avg_glucose_level        bmi   smoking_status  stroke  gender_Male  \
0             228.69  36.600000  formerly smoked       1         True
1             202.21  28.893237     never smoked       1        False
2             105.92  32.500000     never smoked       1         True
3             171.23  34.400000           smokes       1        False
4             174.12  24.000000     never smoked       1        False

   gender_Other  work_type_Never_worked  work_type_Private  \
0         False                   False               True
1         False                   False              False
2         False                   False               True
3         False                   False               True
4         False                   False              False

   work_type_Self-employed  work_type_children
0                    False               False
1                     True               False
2                    False               False
3                    False               False
4                     True               False
(5110, 15)

In [165]:

df = df.astype({col: int for col in df.select_dtypes(bool).columns})

In [166]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['ever_married'] = le.fit_transform(df['ever_married'])
df['Residence_type'] = le.fit_transform(df['Residence_type'])

print(df[['ever_married', 'Residence_type']].head())

   ever_married  Residence_type
0             1               1
1             1               0
2             1               0
3             1               1
4             1               0

In [167]:
smoking_map = {
    'Unknown': 0,
    'never smoked': 1,
    'formerly smoked': 2,
    'smokes': 3
}

df['smoking_status'] = df['smoking_status'].map(smoking_map)

print(df['smoking_status'])

0       2
1       1
2       1
3       3
4       1
       ..
5105    1
5106    1
5107    1
5108    2
5109    0
Name: smoking_status, Length: 5110, dtype: int64

In [170]:
df.head()

,age,hypertension,heart_disease,ever_married,Residence_type,avg_glucose_level,bmi,smoking_status,stroke,gender_Male,gender_Other,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children
0,1.050950,0,1,1,1,2.706375,1.001234e+00,2,1,1,0,0,1,0,0
1,0.785835,0,0,1,0,2.121559,4.615554e-16,1,1,0,0,0,0,1,0
2,1.625367,0,1,1,0,-0.005028,4.685773e-01,1,1,1,0,0,1,0,0
3,0.255604,0,0,1,1,1.437358,7.154182e-01,3,1,0,0,0,1,0,0
4,1.581181,1,0,1,0,1.501184,-6.357112e-01,1,1,0,0,0,0,1,0

In [169]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scale_cols = ['age', 'bmi', 'avg_glucose_level']
df[scale_cols] = scaler.fit_transform(df[scale_cols])

print(df[scale_cols].head())

        age           bmi  avg_glucose_level
0  1.050950  1.001234e+00           2.706375
1  0.785835  4.615554e-16           2.121559
2  1.625367  4.685773e-01          -0.005028
3  0.255604  7.154182e-01           1.437358
4  1.581181 -6.357112e-01           1.501184